[
    {
        "name": "global_string",
        "split_function": "", 
        "filter_from_file": "splitters/global_string", 
        "enabled": false,
        "type": "global_string"
    },
    {
        "name": "start_string",
        "split_function": "", 
        "filter_from_file": "splitters/start_string", 
        "enabled": false,
        "type": "start_string"
    },
    {
        "name": "smtp_id",
        "split_function": "postfix/\\w+\\[\\d+\\]:\\s*(?:(?P<val>[A-Za-z0-9]{15}):|(?P<no_id>.*))",
        "filter_from_file": "splitters/smtp_id",
        "enabled": true,
        "type": "string"
    },
    {
        "name": "checkpoint_user",
        "split_function": " (?:user|dst_user_name)=\"(?:.*?\\()?(?P<username>[a-zA-Z0-9._-]+)\\s*(?:\\))?\"",
        "filter_from_file": "splitters/checkpoint_user",
        "enabled": false,
        "type": "string"
    },
    {
        "name": "checkpoint_user_dn",
        "split_function": " (?:src|dst)_user_dn=\"(?P<user_dn>.*?)\\s*\"",
        "filter_from_file": "splitters/checkpoint_user_dn",
        "enabled": false,
        "type": "string"
    },
    {
        "name": "checkpoint_session_uid",
        "split_function": " session_uid=\"(?P<session_uid>.*?)\"",
        "filter_from_file": "splitters/checkpoint_session_uid",
        "enabled": false,
        "type": "string"
    },
    {
        "name": "checkpoint_xlatesrc",
        "split_function": " xlatesrc=\"(?P<xlatesrc>.*?)\"",
        "filter_from_file": "splitters/checkpoint_xlatesrc",  
        "enabled": false,
        "type": "ip"
    },
    {
        "name": "checkpoint_src",
        "split_function": " src=\"(?P<src>.*?)\"",
        "filter_from_file": "splitters/checkpoint_src",  
        "enabled": false,
        "type": "ip"
    },
    {
        "name": "checkpoint_dst",
        "split_function": " dst=\"(?P<dst>.*?)\"",
        "filter_from_file": "splitters/checkpoint_dst",
        "enabled": false,
        "type": "ip"
    },
    {
        "name": "checkpoint_status",
        "split_function": " status=\"(?P<status>.*?)\"",
        "filter_from_file": "splitters/checkpoint_status",
        "enabled": false,
        "type": "string"
    },
    {
        "name": "checkpoint_action",
        "split_function": " action=\"(?P<action>.*?)\"",
        "filter_from_file": "splitters/checkpoint_action",
        "enabled": false,
        "type": "string",
        "comment": "Accept, Detect, Prevent, Drop, Reject, HTTPS Bypass, Redirect, HTTPS Inspect, Bypass, Log In, Log Out, Failed Log In, Block, Allow, Update"
    },
    {
        "name": "checkpoint_client_name",
        "split_function": " client_name=\"(?P<clientname>.*?)\"",
        "filter_from_file": "splitters/checkpoint_client_name",
        "enabled": false,
        "type": "string"
    },
    {
        "name": "checkpoint_office_mode_ip",
        "split_function": " office_mode_ip=\"(?P<officemodeip>.*?)\"",
        "filter_from_file": "splitters/checkpoint_office_mode_ip",
        "enabled": false,
        "type": "ip"
    },
    {
        "name": "checkpoint_service",
        "split_function": " service=\"(?P<service>.*?)\"",
        "filter_from_file": "splitters/checkpoint_service",
        "enabled": false,
        "type": "string"
    },
    {
        "name": "squid_client_ip",
        "split_function": "^\\d+\\.\\d+\\s+\\d+\\s+(?P<src_ip>\\d{1,3}(?:\\.\\d{1,3}){3})",
        "filter_from_file": "splitters/squid_client_ip",
        "enabled": false,
        "type": "ip"
    }    
]
